# Generated by Django 6.0.1 on 2026-05-03 07:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, null=True)),
                ('age', models.DateField(null=True)),
                ('Department', models.CharField(max_length=50, null=True)),
            ],
        ),
    ]
